In [2]:
import pandas as pd
import numpy as np
from io import StringIO
csv_data='''A,B,C,D

10,20,30,40
1.0,2.0,,4.0
5.0,6.0,,8.0
0.0,11.0,12.0,'''

df=pd.read_csv(StringIO(csv_data))
print(df)
print(df.tail())
print(df.head())
print('Number of missing value')
print(df.isnull().sum())
print('data frame as matrix')
print(df.values)

      A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN
      A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN
      A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN
Number of missing value
A    0
B    0
C    2
D    1
dtype: int64
data frame as matrix
[[10. 20. 30. 40.]
 [ 1.  2. nan  4.]
 [ 5.  6. nan  8.]
 [ 0. 11. 12. nan]]


In [3]:
from sklearn.impute import SimpleImputer
imput=SimpleImputer(missing_values=np.nan,strategy='mean')
imput=imput.fit(df)
imputed_data=imput.transform(df.values)
print("Imputed_data:\n",imputed_data)

Imputed_data:
 [[10.         20.         30.         40.        ]
 [ 1.          2.         21.          4.        ]
 [ 5.          6.         21.          8.        ]
 [ 0.         11.         12.         17.33333333]]


In [4]:
imput=SimpleImputer(missing_values=np.nan,strategy='median')
imput=imput.fit(df)
imputed_data=imput.transform(df.values)
print("Imputed_data:\n",imputed_data)

Imputed_data:
 [[10. 20. 30. 40.]
 [ 1.  2. 21.  4.]
 [ 5.  6. 21.  8.]
 [ 0. 11. 12.  8.]]


In [5]:
df1=df.dropna()
print(df1)

      A     B     C     D
0  10.0  20.0  30.0  40.0


In [6]:
df2=df.dropna(axis=1)
print(df2)

      A     B
0  10.0  20.0
1   1.0   2.0
2   5.0   6.0
3   0.0  11.0


In [9]:
print(df.dropna(how='all'))


      A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN


In [11]:
df4=df.dropna(thresh=3)
print(df4)

      A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN


In [12]:
print(df.dropna(subset=['C']))

      A     B     C     D
0  10.0  20.0  30.0  40.0
3   0.0  11.0  12.0   NaN
