In [1]:
pwd

'/home/vikas'

In [2]:
cd /home/vikas/Documents/datasets

/home/vikas/Documents/datasets


In [3]:
pwd

'/home/vikas/Documents/datasets'

In [4]:
import pandas as pd

In [5]:
data=pd.read_csv('data.csv')
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M       17.990         10.38          122.80     1001.0   
1      842517         M       20.570         17.77          132.90     1326.0   
2    84300903         M       19.690         21.25          130.00     1203.0   
3    84348301         M       11.420         20.38           77.58      386.1   
4    84358402         M       20.290         14.34          135.10     1297.0   
5      843786         M       12.450         15.70           82.57      477.1   
6      844359         M       18.250         19.98          119.60     1040.0   
7    84458202         M       13.710         20.83           90.20      577.9   
8      844981         M       13.000         21.82           87.50      519.8   
9    84501001         M       12.460         24.04           83.97      475.9   
10     845636         M       16.020         23.24          102.70      797.8   
11   84610002         M       15.780         17.89          103.60      781.0   
12     846226         M       19.170         24.80          132.40     1123.0   
13     846381         M       15.850         23.95          103.70      782.7   
14   84667401         M       13.730         22.61           93.60      578.3   
15   84799002         M       14.540         27.54           96.73      658.8   
16     848406         M       14.680         20.13           94.74      684.5   
17   84862001         M       16.130         20.68          108.10      798.8   
18     849014         M       19.810         22.15          130.00     1260.0   
19    8510426         B       13.540         14.36           87.46      566.3   
20    8510653         B       13.080         15.71           85.63      520.0   
21    8510824         B        9.504         12.44           60.34      273.9   
22    8511133         M       15.340         14.26          102.50      704.4   
23     851509         M       21.160         23.04          137.20     1404.0   
24     852552         M       16.650         21.38          110.00      904.6   
25     852631         M       17.140         16.40          116.00      912.7   
26     852763         M       14.580         21.53           97.41      644.8   
27     852781         M       18.610         20.25          122.10     1094.0   
28     852973         M       15.300         25.27          102.40      732.4   
29     853201         M       17.570         15.05          115.00      955.1   
..        ...       ...          ...           ...             ...        ...   
539    921362         B        7.691         25.44           48.34      170.4   
540    921385         B       11.540         14.44           74.65      402.9   
541    921386         B       14.470         24.99           95.81      656.4   
542    921644         B       14.740         25.42           94.70      668.6   
543    922296         B       13.210         28.06           84.88      538.4   
544    922297         B       13.870         20.70           89.77      584.8   
545    922576         B       13.620         23.23           87.19      573.2   
546    922577         B       10.320         16.35           65.31      324.9   
547    922840         B       10.260         16.58           65.85      320.8   
548    923169         B        9.683         19.34           61.05      285.7   
549    923465         B       10.820         24.21           68.89      361.6   
550    923748         B       10.860         21.48           68.51      360.5   
551    923780         B       11.130         22.44           71.49      378.4   
552    924084         B       12.770         29.43           81.35      507.9   
553    924342         B        9.333         21.94           59.01      264.0   
554    924632         B       12.880         28.92           82.50      514.3   
555    924934         B       10.290         27.61           65.67      321.4   
556    924964         B       10.160      

In [8]:
data.shape

(150, 5)

In [9]:
data.describe()

Feature-1   Feature-2   Feature-3   Feature-4
count  142.000000  137.000000  143.000000  141.000000
mean     5.859859    3.067153    3.788811    1.194326
std      0.840387    0.437928    1.749531    0.770693
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [10]:
data.shape[0]

150

In [11]:
data.shape[1]

5

In [12]:
data.head(20)

Feature-1  Feature-2  Feature-3  Feature-4 Class_Label
0         5.1        3.5        1.4        0.2     Class-1
1         4.9        3.0        1.4        0.2     Class-1
2         4.7        3.2        1.3        0.2     Class-1
3         4.6        3.1        1.5        0.2     Class-1
4         5.0        3.6        1.4        0.2     Class-1
5         5.4        3.9        1.7        0.4     Class-1
6         4.6        3.4        1.4        0.3     Class-1
7         5.0        3.4        1.5        0.2     Class-1
8         4.4        2.9        1.4        0.2     Class-1
9         4.9        3.1        1.5        0.1     Class-1
10        5.4        3.7        1.5        0.2     Class-1
11        4.8        3.4        1.6        0.2     Class-1
12        4.8        3.0        1.4        0.1     Class-1
13        4.3        3.0        1.1        0.1     Class-1
14        5.8        4.0        1.2        0.2     Class-1
15        5.7        4.4        1.5        0.4     Class-1
16        5.4        3.9        1.3        0.4     Class-1
17        5.1        3.5        1.4        0.3     Class-1
18        5.7        3.8        1.7        0.3     Class-1
19        5.1        3.8        1.5        0.3     Class-1

In [13]:
data.columns

Index(['Feature-1', 'Feature-2', 'Feature-3', 'Feature-4', 'Class_Label'], dtype='object')

In [14]:
print('Number of records\n:')
print(data['Class_Label'].value_counts())

Number of records
:
Class-1    50
Class-3    50
Class-2    50
Name: Class_Label, dtype: int64


In [15]:
print('Total number of class\n:')
print(data.Class_Label.nunique())

Total number of class
:
3


In [16]:
data.tail(20)

Feature-1  Feature-2  Feature-3  Feature-4 Class_Label
130        7.4        2.8        6.1        1.9     Class-3
131        7.9        3.8        6.4        2.0     Class-3
132        6.4        2.8        5.6        2.2     Class-3
133        6.3        2.8        5.1        NaN     Class-3
134        6.1        2.6        5.6        NaN     Class-3
135        7.7        3.0        6.1        NaN     Class-3
136        6.3        3.4        5.6        2.4     Class-3
137        6.4        3.1        5.5        1.8     Class-3
138        6.0        3.0        4.8        1.8     Class-3
139        6.9        3.1        5.4        2.1     Class-3
140        6.7        3.1        5.6        2.4     Class-3
141        6.9        3.1        NaN        2.3     Class-3
142        5.8        2.7        NaN        1.9     Class-3
143        6.8        3.2        NaN        2.3     Class-3
144        6.7        3.3        5.7        2.5     Class-3
145        6.7        3.0        5.2        2.3     Class-3
146        6.3        2.5        5.0        1.9     Class-3
147        6.5        3.0        5.2        2.0     Class-3
148        6.2        3.4        5.4        2.3     Class-3
149        5.9        3.0        5.1        1.8     Class-3

In [17]:
import numpy as np
class_maping={label:idx for idx,label in enumerate(np.unique(data['Class_Label']))}
#class_maping={'class-1':0,'class-2':1,'class-3':2}
print("\n",class_maping)
print("\n")
data['Class_Label']=data['Class_Label'].map(class_maping)
print(data)
print()
print(data.Class_Label.value_counts)


 {'class-1': 0, 'class-2': 1, 'class-3': 2}


     Feature-1  Feature-2  Feature-3  Feature-4  Class_Label
0          5.1        3.5        1.4        0.2          NaN
1          4.9        3.0        1.4        0.2          NaN
2          4.7        3.2        1.3        0.2          NaN
3          4.6        3.1        1.5        0.2          NaN
4          5.0        3.6        1.4        0.2          NaN
5          5.4        3.9        1.7        0.4          NaN
6          4.6        3.4        1.4        0.3          NaN
7          5.0        3.4        1.5        0.2          NaN
8          4.4        2.9        1.4        0.2          NaN
9          4.9        3.1        1.5        0.1          NaN
10         5.4        3.7        1.5        0.2          NaN
11         4.8        3.4        1.6        0.2          NaN
12         4.8        3.0        1.4        0.1          NaN
13         4.3        3.0        1.1        0.1          NaN
14         5.8        4.0        1.2  

In [18]:
print('Number of missing value')
print(data.isnull().sum())

Number of missing value
Feature-1        8
Feature-2       13
Feature-3        7
Feature-4        9
Class_Label    150
dtype: int64


In [19]:
df1=data.dropna()
print(df1)


Empty DataFrame
Columns: [Feature-1, Feature-2, Feature-3, Feature-4, Class_Label]
Index: []


In [20]:
print('total num of row now left:',df1.shape[0])

total num of row now left: 0


In [21]:
print(df1.Class_Label.value_counts)

<bound method IndexOpsMixin.value_counts of Series([], Name: Class_Label, dtype: float64)>


In [22]:
from sklearn.impute import SimpleImputer
imput=SimpleImputer(missing_values=np.nan,strategy='mean')
imput=imput.fit(data)
imputed_data=imput.transform(data.values)
print("Imputed_data:\n",imputed_data)
imputed_data=pd.DataFrame(imputed_data)


Imputed_data:
 [[5.1        3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [4.7        3.2        1.3        0.2       ]
 [4.6        3.1        1.5        0.2       ]
 [5.         3.6        1.4        0.2       ]
 [5.4        3.9        1.7        0.4       ]
 [4.6        3.4        1.4        0.3       ]
 [5.         3.4        1.5        0.2       ]
 [4.4        2.9        1.4        0.2       ]
 [4.9        3.1        1.5        0.1       ]
 [5.4        3.7        1.5        0.2       ]
 [4.8        3.4        1.6        0.2       ]
 [4.8        3.         1.4        0.1       ]
 [4.3        3.         1.1        0.1       ]
 [5.8        4.         1.2        0.2       ]
 [5.7        4.4        1.5        0.4       ]
 [5.4        3.9        1.3        0.4       ]
 [5.1        3.5        1.4        0.3       ]
 [5.7        3.8        1.7        0.3       ]
 [5.1        3.8        1.5        0.3       ]
 [5.4        3.4        1.7        0.2       

In [23]:
print('total num of row now left:',data.shape[0])
print(data.Class_Label.value_counts)

total num of row now left: 150
<bound method IndexOpsMixin.value_counts of 0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
29    NaN
       ..
120   NaN
121   NaN
122   NaN
123   NaN
124   NaN
125   NaN
126   NaN
127   NaN
128   NaN
129   NaN
130   NaN
131   NaN
132   NaN
133   NaN
134   NaN
135   NaN
136   NaN
137   NaN
138   NaN
139   NaN
140   NaN
141   NaN
142   NaN
143   NaN
144   NaN
145   NaN
146   NaN
147   NaN
148   NaN
149   NaN
Name: Class_Label, Length: 150, dtype: float64>


In [24]:
y=data.Class_Label


In [25]:
x=data.iloc[:,0:4].values
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [nan nan nan 0.2]
 [nan nan nan 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 nan nan nan]
 [5.  nan nan nan]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [26]:
from sklearn.model_selection import train_test_split


In [27]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [28]:
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


In [29]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()

In [30]:
X_train_std=st.fit_transform(X_train)
X_test_std=st.transform(X_test)

In [31]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()


In [32]:
X_train_norm=mms.fit_transform(X_train)
X_test_norm=mms.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(penalty='l1')


In [34]:
lr.fit(X_train_std,y_train)

/home/vikas/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [111]:
y_pre=lr.predict(X_test_std)

lr.score(X_test_std,y_test)

NotFittedError: This LogisticRegression instance is not fitted yet

In [112]:
from sklearn.metrics import confusion_matrix,classification_report
cmat= confusion_matrix(y_pre,y_test)
print(cmat)

NameError: name 'y_pre' is not defined